/*
🔹 Difficulty: 1100

You are given a string s of length n. Let's define two operations you can apply on the string:
1. remove the first character of the string;
2. remove the second character of the string.
Your task is to find the number of distinct non-empty strings that can be generated by applying the given operations 
on the initial string any number of times (possibly zero), in any order.

*/

#include<bits/stdc++.h>
using namespace std;

vector<int> dp;



int main()
{
    int t;
    cin >> t;

    while (t--)
    {
        string str;
        cin >> str;
        
        dp.resize()

        int ans = rec(str);
    }
    
}